### ISSUE TITLE
0.14 migration guide?  More haddocks for estimate?

### ISSUE THREAD

**Issue by rrnewton** [bos/statistics#101]
The new type of `Estimate` is super polymorphic, and it's hard to figure out what should go in that `e` param.  Some examples in the haddocks would help.

Some of this information is already in `changelog.md`, but I think it would help for it to be right in the haddocks for `Estimate`.

**Comment by Shimuuar** [comment]
Thank you for suggestion. I''ll fix it on Firday

**Comment by Shimuuar** [comment]
Fixed in e74a8a73a49fb1d42eaa57d4608894471d33e9a3

It's not complete migration guide but I added notes to about migration to haddock for new/changed data types
