### ISSUE TITLE
How to generate random numbers from a distribution with "statistics" package?

### ISSUE THREAD

**Issue by yuhangwang** [bos/statistics#103]
Could you give an example on how to use this package to generate random numbers from a distribution (say Gaussian) using this "statistics" package? I only found an example on KDE in the example folder which I have added to your wiki (https://github.com/bos/statistics/wiki ). Thanks.

**Comment by jsermeno** [comment]
Take a look at issue https://github.com/bos/statistics/issues/87.

**Comment by yuhangwang** [comment]
Thanks!
