### ISSUE TITLE
Statistics.Distribution.Normal wrongly throws error when standard deviation is 0

### ISSUE THREAD

**Issue by ozataman** [bos/statistics#104]
Unless I am mistaken about the mathematics of this, a standard deviation of 0 should be allowed, as it would naturally occur when values of all samples are equal or if there is only a single sample (a special case of the former). 

This currently raises an error due to the following code:

``` haskell
-- | Create normal distribution from parameters.
--
-- IMPORTANT: prior to 0.10 release second parameter was variance not
-- standard deviation.
normalDistr :: Double            -- ^ Mean of distribution
            -> Double            -- ^ Standard deviation of distribution
            -> NormalDistribution
normalDistr m sd
  | sd > 0    = ND { mean       = m
                   , stdDev     = sd
                   , ndPdfDenom = log $ m_sqrt_2_pi * sd
                   , ndCdfDenom = m_sqrt_2 * sd
                   }
  | otherwise =
    error $ "Statistics.Distribution.Normal.normalDistr: standard deviation must be positive. Got " ++ show sd
```

**Comment by szabi** [comment]
Now just try to calculate` log $ m_sqrt_2_pi * sd where sd = 0`...

**Comment by ozataman** [comment]
I certainly see your point, thanks. But the question is where you want your program to blow up, I guess. In the current version, "sample" blows up even if you have a legitimate dataset that just happens to have a constant value. In your example, you blow up down the line. 

Don't get me wrong, I do fully understand the rationale of ensuring guarantees once you form the `NormalDistribution`. Thanks for the response.

**Comment by Shimuuar** [comment]
I think better option is to create type class like: 

```
class FromSample d where
  type SampleType d
  fromSample :: Vector (SampleType d) -> Maybe d
```

This way it's possible to return Nothing when there's not enough data to create distribution from sample and it generalizes to several distributions.
