### ISSUE TITLE
Should `mean` also have an INLINE pragma?

### ISSUE THREAD

**Issue by fhaust** [bos/statistics#115]
I just wondered why [mean](http://hackage.haskell.org/package/statistics-0.13.3.0/docs/Statistics-Sample.html#v:mean) doesn't have an `INLINE` pragma. I guess you are aware that this will prevent stream fusion, so I expect there to be another reason especially because there are `INLINES` on other functions?

**Comment by Shimuuar** [comment]
I don't really know. Commit which replaced INLINE with SPECIALIZE pragmas doesn't either. Maybe to avoid having multiple copies of `mean` etc in executable. Please reopen if it causes performance problems for you.

**Comment by fhaust** [comment]
I don't have any hard measurements, but from experience inlining calls to vector is faster in most cases. On the other hand the current `mean` implementation does two folds (ie traversals) which is slow in any case :-)
