### ISSUE TITLE
Timeline for new release

### ISSUE THREAD

**Issue by ndmitchell** [bos/statistics#116]
I'm waiting for a few bug fixes that are in the HEAD, but not the last released version. Is there any idea when the next version will be released? I'm grateful for all the work, and not trying to hassle, just trying to plan some stuff.

CC @Shimuuar

**Comment by Shimuuar** [comment]
Sorry for the wait.I've been busy lattely. I'll try to make release on the weekend

**Comment by ndmitchell** [comment]
Any idea of the timeline?

**Comment by Shimuuar** [comment]
Sorry about that. I got seriously ill and couldn't do anything for last three weeks. So hopefully next weekend

**Comment by ndmitchell** [comment]
Sorry to hear that, hope you are feeling better now. No rush on my side, just trying to make plans :)

**Comment by Shimuuar** [comment]
I just uploaded 0.14. Sorry for the delays

@bos ^^
