### ISSUE TITLE
`jackknifeVarianceUnb` fails for input of length 2

### ISSUE THREAD

**Issue by patrickdoc** [bos/statistics#140]
While investigating Criterion [issue #162](https://github.com/bos/criterion/issues/162), I've uncovered an problem with the jackknife calculations.

https://github.com/bos/statistics/blob/98a5e888ab411b3f48d31bb677b4c8f1db880217/Statistics/Resampling.hs#L223-L245

When the input is of length 2, `q` is 1. For `jackknifeVarianceUnb`, `c` will also be 1. This means that at the very least, `go` will divide everything by 0.

Additionally, if my algebra skills haven't failed me, `al + ar - (b * b)` will always be 0, so `go` is just `(0/1)/0 = NaN` for both elements of the sample.

**Comment by Shimuuar** [comment]
Thank you! `jackknife` works by throwing out every other sample and if sample have two elements jackknife will try to estimate variance for two one-element sample and will fail. 

I'll add call to error for 2-element sample and variance/standard deviation. But it's part of more general problem (#100)

**Comment by Shimuuar** [comment]
fixed in d842eb7c9af0e160a61455be9e4a3062aec96862
