### ISSUE TITLE
bootStrapBCA causes vector index out of bounds

### ISSUE THREAD

**Issue by harendra-kumar** [bos/statistics#149]
I reduced the crash to the following input set.

```haskell
    let v = U.fromList [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0]
        r = Bootstrap {fullSample = 0.21821789023599236, resamples = U.fromList [0.0,0.0,0.21821789023599236,0.21821789023599236,0.30079260375911915,0.30079260375911915,0.30079260375911915,0.30079260375911915]}
    bootstrapBCA cl95 v [(StdDev, r)]
```

In the code I see this:

```haskell
        lo    = max (cumn a1) 0
          where a1 = bias + b1 / (1 - accel * b1)
                b1 = bias + z1
        hi    = min (cumn a2) (ni - 1)
          where a2 = bias + b2 / (1 - accel * b2)
                b2 = bias - z1
```

It is clipping one side of the index range (either max or min) in `lo` and `hi` but the other side could still go wrong.

I ran into this when performing benchmark analysis in the [bench-graph](https://github.com/composewell/bench-graph) package. But I think this may also be the source of a long standing crash in criterion. See https://github.com/bos/criterion/issues/162 .  cc @RyanGlScott

We can clip the indices to stay within range, but I am not sure if this also means that there is a problem with algorithm itself.

**Comment by RyanGlScott** [comment]
I had to put this code into a standalone file to see what was going on for myself:

```haskell
module Main where

import qualified Data.Vector.Unboxed as U
import Statistics.Resampling
import Statistics.Resampling.Bootstrap
import Statistics.Types

main :: IO ()
main =
    let v = U.fromList [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0]
        r = Bootstrap {fullSample = 0.21821789023599236, resamples = U.fromList [0.0,0.0,0.21821789023599236,0.21821789023599236,0.30079260375911915,0.30079260375911915,0.30079260375911915,0.30079260375911915]}
    in print $ bootstrapBCA cl95 v [(StdDev, r)]
```
```
$ /opt/ghc/8.4.3/bin/runghc Bug.hs
Bug.hs: ./Data/Vector/Generic.hs:245 ((!)): index out of bounds (-9223372036854775808,8)
CallStack (from HasCallStack):
  error, called at ./Data/Vector/Internal/Check.hs:87:5 in vector-0.12.0.1-GC2xzdMF0QQGz7ZCcRBJRL:Data.Vector.Internal.Check
^C
```

**Comment by harendra-kumar** [comment]
After fixing this I hit a similar problem in `bootstrapRegress`. I did not spend the time to create a minimal example in that case but just fixed the bounds and it fixed the crash. This function is also used in criterion, so this may also be the culprit in some such crashes reported.

**Comment by Shimuuar** [comment]
I merged both PRs and uploaded long overdue release 0.15.0.0 to hackage. It contain number of other API changes so it may break something. 

Sorry for delay

**Comment by harendra-kumar** [comment]
Thanks @Shimuuar ! The release was quick, I did not expect it so fast.
