### ISSUE TITLE
Does it build with GHC 8.8.1?

### ISSUE THREAD

**Issue by mrkkrp** [bos/statistics#156]
I do not understand what is going on. `criterion` seem to build with GHC 8.8.1 now, at least according to its Travis CI runs. However, I'm trying to compile Megaparsec with GHC 8.8.1 and here is what I get:

https://travis-ci.org/mrkkrp/megaparsec/jobs/579429690#L278

It looks like the root of the problem is that `criterion` (which is a dependency of the benchmarks) depends on `statistics` which in turn depends on `vector-th-unbox`, which has uncompatible constraint for `base` and `template-haskell`. Can we resolve this somehow?

**Comment by Shimuuar** [comment]
`statistics` does depends in `vector-th-unbox`, so at the moment it shouldn't work. Hopefully `vector-th-unbox` will be fixed soon

With criterion. Maybe if one ptaches out all uses if `vector-th-unbox` it will build?

**Comment by mrkkrp** [comment]
I was told this is `vector-th-unbox` issue, and its maintainer is not responding. I'm going to close this issue because I think it's not a problem with `statistics`.
