### ISSUE TITLE
Statistical tests should return p-value 

### ISSUE THREAD

**Issue by Shimuuar** [bos/statistics#25]
At the moment statistical tests just return whether null hypotheis is rejected or not. That's not sufficient. It's quite different to reject hypothesys at p=1e-18 and at p =0.03. 

  1. Test significance
  1. Test p-value. Caller have that information still it's not nice to force him to track that info
  2. Calculated p-value
  1. Whatever else particular test wants to provide

**Comment by Shimuuar** [comment]
I think work on this is mostly complete. Documentaion and chagelog still need some work though. If anyone wants to give feedback please chack out branch `confidence`

**Comment by Shimuuar** [comment]
Fixed

**Comment by GregorySchwartz** [comment]
As of 0.13.3.0 I do not see p values returned in Mann Whitney U, is this closed for some other reason?
