### ISSUE TITLE
histogram_ fails to build with GHC HEAD

### ISSUE THREAD

**Issue by nomeata** [bos/statistics#65]
this is still minor, as it only applies to GHC HEAD, but this is a heads-up nevertheless, as it will apply to GHC 7.10. Something changed (possibly in `vector` or in GHC) and `histogram_` fails to compile because it has trouble figuring out how to instantiate the `s` variable.  I have a hack at https://ghc.haskell.org/trac/ghc/attachment/ticket/9190/statistics-0.11.0.3.patch to continue working, but not a proper patch at this moment.

**Comment by Shimuuar** [comment]
Is it still an issue with 7.10? I don't have it at hand yet, so I can't test

**Comment by Shimuuar** [comment]
Well 7.10 is out for a long time everything is fine. I assume problem resolved itself somehow
