### ISSUE TITLE
Incorrect behavior of kolmogorovSmirnovTest2

### ISSUE THREAD

**Issue by tranma** [bos/statistics#81]
Hi, I have some questions about the kolmogorovSmirnov 2-sample test. This is the behaviour I got:

```
> let xs = Data.Vector.Unboxed.empty
> kolmogorovSmirnovTest2 0.05 xs xs
NotSignificant
> let xs = Data.Vector.Unboxed.fromList [1]
> kolmogorovSmirnovTest2 0.05 xs xs
Significant
```

I thought if you use this test on one sample, it should be `NotSignificant`, regardless of how the sample looks like, because a sample should have the same distribution as itself? Should there be a special case here, or am I missing something?

disclaimer: I don't really know anything about stats.

**Comment by Shimuuar** [comment]
Empty samples should be definitely special-cased since it's not possible to defined empirical CDF in any meaningful way. 

Second test looks like a bug to me.
