### ISSUE TITLE
binomial probability density function returns NaN for large values of n

### ISSUE THREAD

**Issue by etep** [bos/statistics#83]
For example, with 10 million trials, a probability of success of 1 in 10 thousand, and evaluating at k=1000:

    >> % in matlab:
    >> n = 10e6;
    >> b = 10e3;
    >> p = 1/b;
    >> e = n/b;
    >> binopdf( e, n, p )
    >> 
    >> ans = 0.0126

But using Haskell, this returns NaN:

    > -- in ghci:
    > import Statistics.Distribution.Binomial
    > import Statistics.Distribution
    > let n = 10000000
    > let p = (1.0/10000.0) :: Double
    > let b = 10000
    > let bd = binomial n p
    > let e = n `div` b
    > probability bd e
    > NaN

And perhaps this is obvious, but you can do the following:

    > let p0 = cumulative bd 999.5
    > let p1 = cumulative bd 1000.5
    > p1 - p0
    > 1.2615242126970017e-2

**Comment by Shimuuar** [comment]
Cause of this bug is obvious: `Numeric.SpecFunctions.choose` overflows for big enough inputs. Fix simple switch to log-domain for calculations. 

Thank you for report
