### ISSUE TITLE
behaviour of Statistics.Quantile.weightedAvg is not fully consistent with its documentation

### ISSUE THREAD

**Issue by mohrm** [bos/statistics#92]
The [documentation](https://hackage.haskell.org/package/statistics-0.13.2.3/docs/Statistics-Quantile.html) says:

> The number of quantiles is described below by the variable q, so with q=4, a 4-quantile (also known as a quartile) has 4 intervals, and contains 5 points. The parameter k describes the desired point, where 0 ≤ k ≤ q.

This clearly includes the corner case `k=q`, so I expect that `weightedAvg q q sample` is a valid usage of this function. Instead I get an exception:

`Statistics.Quantile> weightedAvg 4 4 $ V.fromList [0..1000]
*** Exception: Statistics.Quantile.weightedAvg: Wrong quantile number`

From my point of view, either the documentation or the code should be changed.

**Comment by Shimuuar** [comment]
Thank you for the report. In this case documentation is right and code is wrong.

**Comment by nomeata** [comment]
I just stumbled over this as well. This has not been released, yet, as it?

Also, if you special-case `k == q` with a call to `maximum`, why not special-case `k == 0` with a call to `minimum`?
