### ISSUE TITLE
weightedAvg throws "index out of bounds" exception

### ISSUE THREAD

**Issue by nmattia** [bos/statistics#94]
When `weightedAvg` is called on an empty vector the following exception is thrown:

    > import Statistics.Quantile as Q
    > import Data.Vector as V
    > Q.weightedAvg $ V.fromList []
     *** Exception: ./Data/Vector/Generic.hs:235 ((!)): index out of bounds (-1,0)

Unfortunately most input errors seem to be handling with exceptions. To be nice to the user, the error could be made more explicit:

    > import Statistics.Quantile as Q
    > import Data.Vector as V
    > Q.weightedAvg $ V.fromList []
     *** Exception: Statistics.Quantile.weightedAvg: Sample is empty

`mean` and `welfordMean` return `NaN` and `0` resp. on empty input. Would that be a solution? Either way, it would be good to document which parameters can be used such that the user can be extra careful.

**Comment by Shimuuar** [comment]
I agree library function should not throw out of bounds access errors. They aren't more helpful than dreaded `Prelude.head: empty list`.

Situation with mean is little trickier. Mean is not defined for empty sample so we have to either throw error for empty sample or wrap result in Maybe or add define result for empty sample. Both `mean` and `welfordMean` are defined in terms of left fold so there's base case for empty sample and it happens to be NaN and 0 respectively.

**Comment by nmattia** [comment]
Same applies for quantiles, they're not defined for an empty input. I guess the ideal solution would indeed be to wrap everything in `Maybe`s, or provide an alternative package/module like [safe](https://hackage.haskell.org/package/safe) to avoid breaking compatibility. Though I believe that a meaningful error message is already an improvement over the current behavior. Feel free to close this if it's satisfactory.

**Comment by Shimuuar** [comment]
I'm closing this in favor of #100. Problem with weightedAvg is fixed and other issue is more general
