### ISSUE TITLE
"Continuous" spelled incorrectly in many places in Statistics.Distribution source

### ISSUE THREAD

**Issue by cspollard** [bos/statistics#96]
"Continuous" is misspelled "continous" in many places in Statistics/Distribution.hs. Since this is so simple, I am creating an issue. If you would like a pull request, I can do that.

Chris

**Comment by Shimuuar** [comment]
Thank you! Comments are fixed in 98b389f9a3eeee6aba5efb9884213ec9ea6c96ee  and 921b0e8403a0ae465fb520bb7d49f995d383a5c8. 

There's function with spelling error as well. It's fixed in development branch but not in master.
