### ISSUE TITLE
Newest QuickCheck breaks t_fftInverse property

### ISSUE THREAD

**Issue by nick8325** [bos/statistics#97]
In the latest QuickCheck, `t_fftInverse` will only be tested 1 time, not 100. This is because QuickCheck now assumes that any property without a `forAll` (or similar) is deterministic.

The easiest way to fix it is to use a normal quantifier instead of `MkProperty`. Using the `Blind` modifier you can get something that doesn't need a `Show` instance, which won't break in the future:

```
t_fftInverse :: (HasNorm (U.Vector a), U.Unbox a, Num a, Show a, Arbitrary a)
             => (U.Vector a -> U.Vector a) -> Property
t_fftInverse roundtrip =
  forAll (Blind <$> genFftVector) $ \(Blind x) ->
  let n  = G.length x
      x' = roundtrip x
      d  = G.zipWith (-) x x'
      nd = vectorNorm d
      nx = vectorNorm x in
    counterexample "Original vector"
  $ counterexample (show x )
  $ counterexample "Transformed one"
  $ counterexample (show x')
  $ counterexample (printf "Length = %i" n)
  $ counterexample (printf "|x - x'| / |x| = %.6g" (nd / nx))
  $ nd <= 3e-14 * nx
```

Alternatively, you can wrap the property in `again` to tell QuickCheck that it's nondeterministic.

**Comment by Shimuuar** [comment]
Thank you for the report! Fixed in development branch
